mod choice_hero_3123_weapon;
mod get_hero_birthday;
mod hero_default_equip;
mod hero_info_list;
mod hero_level_up;
mod hero_rank_up;
mod hero_red_dot_read;
mod hero_touch;
mod hero_upgrade_skill;
mod mark_hero_favor;
mod set_show_hero_unique_ids;
mod unmark_is_new;

pub use choice_hero_3123_weapon::on_choice_hero_3123_weapon;
pub use get_hero_birthday::on_get_hero_birthday;
pub use hero_default_equip::on_hero_default_equip;
pub use hero_info_list::on_hero_info_list;
pub use hero_level_up::on_hero_level_up;
pub use hero_rank_up::on_hero_rank_up;
pub use hero_red_dot_read::on_hero_red_dot_read;
pub use hero_touch::on_hero_touch;
pub use hero_upgrade_skill::on_hero_upgrade_skill;
pub use mark_hero_favor::on_mark_hero_favor;
pub use set_show_hero_unique_ids::on_set_show_hero_unique_ids;
pub use unmark_is_new::on_unmark_is_new;
